<div class="admin-features-block">
  <h2>Ajouter un article sur votre blog</h2>
  <form action="index.php?admin=add_article" method="post" class="form-features" enctype="multipart/form-data">
    <div class="field">
      <label for="article_title">Titre de l'article</label>
      <input type="text" name="article_title" required>
    </div>
    <div class="field textarea">
      <label for="article_content">Contenu de l'article </label>
      <textarea name="article_content" ></textarea>
    </div>
    <div class="field">
      <label for="image_src">Insérer votre image</label>
      <input type="file" accept="image/png, image/jpeg" name="image_src" required>
    </div>
    <div class="field">
      <label for="image_alt">Entrer la description de l'image </label>
      <input type="text" name="image_alt" required>
    </div>
    <div class="field">
      <input type="submit" value="Ajouter">
    </div>
  </form>
</div>