<?php if($this -> isConnectAdmin()) : ?>
  <div class="admin-features-bg">
    <div class="container">
      <div class="admin-features-choice">
        <div>
          <a href="index.php?admin=login&add_product">Ajouter un produit</a>
          <a href="index.php?admin=login&delete_product">Supprimer un produit</a>
          <a>Editer un produit</a>
        </div>
        <div>
          <a>Ajouter un article</a>
          <a>Supprimer un article</a>
          <a>Editer un article</a>
          <a>Supprimer un commentaire</a>
          <a>Editer un commentaire</a>
        </div>
        <div>
          <a>Voir toutes les commandes</a>
          <a>Supprimer une commande</a>
          <a>Editer une commande</a>
        </div>
      </div> 
      <div class="admin-features-block">
        <?php if(isset($_GET["add_product"])) : ?>
          <h2>Ajouter un produit</h2>
          <form action="index.php?admin=add_product" method="post" class="form-features" enctype="multipart/form-data">
            <div class="field">
              <label for="product_name">Entrer le nom du produit </label>
              <input type="text" name="product_name" required>
            </div>
            <div class="field textarea">
              <label for="product_description">Entrez la description du produit </label>
              <textarea name="product_description" required></textarea>
            </div>
            <div class="field">
              <label for="product_alt">Entrer la composition du produit </label>
              <input type="text" name="product_alt" required>
            </div>
            <div class="field">
              <label for="product_price">Entrer le prix du produit </label>
              <input type="text" name="price" required>
            </div>
            <div class="field">
              <label for="image_src">Insérer votre image </label>
              <input type="file" accept="image/png, image/jpeg" name="image_src" required>
            </div>
            <div class="field">
              <label for="image_alt">Entrer la description de l'image </label>
              <input type="text" name="image_alt" required>
            </div>
            <div class="field">
              <input type="submit" value="Ajouter">
            </div>
          </form>
        <?php endif; ?>
      </div>
    </div>
  </div>
<?php else : ?>
  <div id="login-modal" class="login-modal" style="display:block">      
    <form action="index.php?admin=login" method="POST">
      <h1>Connexion</h1>
      <?php if(isset($message)): ?>
        <p> <?= $message ?> </p>
      <?php endif; ?>
      <label><b>Nom d'utilisateur</b></label>
      <input type="text" placeholder="Entrer le nom d'utilisateur" name="username" required>
      <label><b>Mot de passe</b></label>
      <input type="password" placeholder="Entrer le mot de passe" name="password" required>
      <input type="submit" id='submit' value='LOGIN' >
    </form>
  </div>
<?php endif; ?>