<?php if($this -> isConnectAdmin()) : ?>
  <div class="admin-features-bg">
    <div class="container">
      <div class="admin-features-choice">
        <div>
          <a href="index.php?admin=login&add_product">Ajouter un produit</a>
          <a href="index.php?admin=login&edit_product">Editer un produit</a>
          <a href="index.php?admin=login&delete_product">Supprimer un produit</a>
        </div>
        <div>
          <a>Ajouter un article</a>
          <a>Supprimer un article</a>
          <a>Editer un article</a>
          <a>Supprimer un commentaire</a>
          <a>Editer un commentaire</a>
        </div>
        <div>
          <a>Voir toutes les commandes</a>
          <a>Supprimer une commande</a>
          <a>Editer une commande</a>
        </div>
      </div> 
      <?php if(isset($templateAdmin)) : ?>
        <?php include $templateAdmin.".phtml" ?>
      <?php endif; ?>
    </div>
  </div>
<?php else : ?>
  <div id="login-modal" class="login-modal" style="display:block">      
    <form action="index.php?admin=login" method="POST">
      <h1>Connexion</h1>
      <?php if(isset($message)): ?>
        <p> <?= $message ?> </p>
      <?php endif; ?>
      <label><b>Nom d'utilisateur</b></label>
      <input type="text" placeholder="Entrer le nom d'utilisateur" name="username" required>
      <label><b>Mot de passe</b></label>
      <input type="password" placeholder="Entrer le mot de passe" name="password" required>
      <input type="submit" id='submit' value='LOGIN' >
    </form>
  </div>
<?php endif; ?>