<div class="article-comments">
  <h3>Commentaires</h3>
  <?php foreach ($comments as $comment) : ?>
    <div class="comments-content">
      <p>Posté par <?= $comment['last_name'] . " " . $comment['name'] ?></p>
      <p>Article : <?= $comment['title'] ?></p>
      <p><em>Le <?= $comment['date_create'] ?></em></p>
      <p><?= $comment['content'] ?></p>
      <a href="index.php?admin=delete_comment&id_comment=<?= $comment['id_comment'] ?>"><button>Supprimer le commentaire</button></a>
    </div>
  <?php endforeach; ?>
</div>