<div class="admin-features-block">
  <h2>Mettre a jour une commande</h2>
  <form action="index.php?admin=edit_order" method="post" class="form-features">
    <div class="field">
      <label for="orders">Veuillez choisir une commande</label>
      <select name="orders" id="orders">
        <option value="default">Numéro de la commande</option>
        <?php foreach ($orders as $order) : ?>
          <option value="<?= $order['id_order'] ?>"><?= $order['id_order'] ?></option>
        <?php endforeach; ?>
      </select>
    </div>
  </form>
  <div>
    <table class="order-table" id="order-table">
      <thead>
        <tr>
          <th>Numéro de la commande</th>
          <th>Prix total</th>
          <th>Date de commande</th>
          <th>Date d'expédition</th>
          <th>Statut</th>
          <th>Nom/Prénom du client</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($orders as $order) : ?>
          <tr>
            <td><?= $order['id_order'] ?></td>
            <td><?= number_format($order['total_price'], 2, ',', ' ',) ?></td>
            <td><?= $order['order_date'] ?></td>
            <td><?= $order['shipped_date'] ?></td>
            <td><?= $order['statut'] ?></td>
            <td><?= $order['lastname'] . " " . $order['name'] ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
  <div id="order-details">

  </div>
</div>
</div>