<div id="login-modal" class="login-modal" style="display:block">      
  <form action="index.php?admin=login" method="POST">
    <h1>Connexion</h1>
    <?php if(isset($message)): ?>
      <p> <?= $message ?> </p>
    <?php endif; ?>
    <label><b>Nom d'utilisateur</b></label>
    <input type="text" placeholder="Entrer le nom d'utilisateur" name="username" required>
    <label><b>Mot de passe</b></label>
    <input type="password" placeholder="Entrer le mot de passe" name="password" required>
    <input type="submit" id='submit' value='LOGIN' >
  </form>
</div>