<!DOCTYPE html>
<html lang="fr-FR">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Camiseta - accueil</title>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
    />
    <link rel="stylesheet" href="css/slick.css" />
    <link rel="stylesheet" href="css/slick-theme.css" />
    <link rel="stylesheet" href="css/variables.css" />
    <link rel="stylesheet" href="css/styles.css" />
    <link rel="stylesheet" href="css/media_queries.css" />
  </head>
  <body>
    <header class="header">
      <div class="logo">
        <img src="img/logo2.png" alt="logo" />
      </div>
      <nav class="header-navbar">
        <ul id="navbar">
          <li id="close" class="close"><i class="fas fa-times"></i></li>
          <li><a href="index.php">Accueil</a></li>
          <li><a href="catalogue.php">Catalogue</a></li>
          <li><a href="blog.php">Blog</a></li>
          <li><a href="about.php">A propos</a></li>
          <li><a href="contact.php">Contact</a></li>
          <li>
            <a href="basket.html" class="lg-bag"
              ><i class="fas fa-shopping-bag"></i
            ></a>
          </li>
        </ul>
      </nav>
      <div class="mobile">
        <a href="basket.html"><i class="fas fa-shopping-bag"></i></a>
        <i class="fas fa-outdent" id="bar"></i>
      </div>
    </header>
    <main>
    <?php require $template.".phtml"?>
    </main>
    <footer class="footer">
      <div class="contact-footer">
        <div class="logo">
          <img src="img/logo2.png" alt="logo" />
        </div>
        <p>Contact</p>
        <address>
          <ul>
            <li>
              <strong>Adresse :</strong> 5 boulevard de la liberté - 35000
              Rennes
            </li>
            <li><strong>Téléphone :</strong> 06 57 82 12 32</li>
            <li>Ouvert du lundi au samedi de 10h à 19h30</li>
          </ul>
        </address>
        <div class="social-network">
          <p>Réseaux sociaux</p>
          <ul>
            <li>
              <a href="https://www.facebook.com/"
                ><i class="fab fa-facebook"></i
              ></a>
            </li>
            <li>
              <a href="https://www.instagram.com/"
                ><i class="fab fa-instagram"></i
              ></a>
            </li>
            <li>
              <a href="https://www.tiktok.com/fr/"
                ><i class="fab fa-tiktok"></i
              ></a>
            </li>
            <li>
              <a href="https://www.youtube.com/fr/"
                ><i class="fab fa-youtube"></i
              ></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="about-footer">
        <p>A propos</p>
        <ul>
          <li><a href="about.php">A propos de nous</a></li>
          <li><a href="">Information sur la livraison</a></li>
          <li><a href="privacy_policy.php">Politique de confidentialité</a></li>
          <li><a href="">Conditions générales</a></li>
          <li><a href="contact.php">Nous contacter</a></li>
        </ul>
      </div>
      <div class="account-footer">
        <p>Mon compte</p>
        <ul>
          <li><a href="">Se connecter</a></li>
          <li><a href="basket.html">Mon panier</a></li>
          <li><a href="">Ma liste de souhait</a></li>
          <li><a href="">Suivre ma commande</a></li>
          <li><a href="">Aide</a></li>
        </ul>
      </div>
      <div class="app-footer">
        <p>Installer l'application</p>
        <div class="logo-store">
          <a href="https://www.apple.com/fr/store"
            ><img src="img/pay/app.jpg" alt="applestore"
          /></a>
          <a href="https://play.google.com/store"
            ><img src="img/pay/play.jpg" alt="playstore"
          /></a>
        </div>
        <p>Paiements sécurisés</p>
        <div class="logo-payment">
          <img src="img/pay/pay.png" alt="logo credit card" />
        </div>
      </div>
    </footer>
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.min.js"
    ></script>
    <script src="js/index.js"></script>
    <script src="js/slick.js"></script>
  </body>
</html>
