<section class="hero container">
  <div class="">
    <div class="hero-block-content">
      <p>Promotion anniversaire</p>
      <h1>Camiseta fête ses 10 ans !</h1>
      <div class="hero-content">
        <p>
          Toujours plus de produits, <br />
          toujours plus de promotions.
        </p>
        <p>
          <em
            >Economisez 20% sur votre commande avec ce code :
            <strong>24BD</strong></em
          >
        </p>
        <a href="catalogue.php">Acheter maintenant</a>
      </div>
    </div>
    <div class="features">
      <div class="fe-box">
        <img src="img/features/f1.png" alt="click & collect" />
        <p>Click & collect</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f2.png" alt="envoi gratuit" />
        <p>Envoi gratuit</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f3.png" alt="economie" />
        <p>Economie</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f4.png" alt="promotion" />
        <p>Promotions</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f5.png" alt="ecologique" />
        <p>Ecologique</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f6.png" alt="SAV 24/24H" />
        <p>SAV 24/24H</p>
      </div>
    </div>
  </div>
</section>
<section class="features-products">
  <h2>Collection été 2022</h2>
  <p>Nouveau design, nouvelles couleurs</p>
  <div class="responsive">
    <?php foreach ($sliderItems1 as $sliderItem) : ?>
    <div>
      <div class="product-box">
        <a href="index.php?action=detailsProduct&id_product=<?= $sliderItem["id_product"] ?>">
          <img src="<?= $sliderItem["image_src"] ?>" alt="<?= $sliderItem["image_alt"] ?>" />
          <div class="product-content">
            <div class="product-description">
              <h3>Camiseta</h3>
              <p><?= $sliderItem["product_name"] ?></p>
              <p><em><?= $sliderItem["product_alt"] ?></em></p>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
            </div>
            <div class="product-price">
              <p><?= $sliderItem["MSRP"] ?> €</p>
              <i class="fas fa-shopping-basket"></i>
            </div>
          </div>
        </a>
      </div>
    </div>
    <?php endforeach; ?>    
  </div>
</section>
<div class="banner banner-1">
  <p>Nouveaux arrivages chaques semaines</p>
  <p>
    Reprise de vos anciens vêtements contre <span>remise</span> sur la nouvelle
    collection
  </p>
  <a href="#">En savoir plus</a>
</div>
<section class="features-products arrival">
  <h2>Nouveaux arrivages</h2>
  <p>Nouveau design, nouvelles couleurs</p>
  <div class="responsive">
    <?php foreach ($sliderItems2 as $sliderItem) : ?>
    <div>
      <div class="product-box">
        <a href="product.php?id_product=<?= $sliderItem["id_product"] ?>">
          <img src="<?= $sliderItem["image_src"] ?>" alt="<?= $sliderItem["image_alt"] ?>" />
          <div class="product-content">
            <div class="product-description">
              <h3>Camiseta</h3>
              <p><?= $sliderItem["product_name"] ?></p>
              <p><em><?= $sliderItem["product_alt"] ?></em></p>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
            </div>
            <div class="product-price">
              <p><?= $sliderItem["MSRP"] ?> €</p>
              <i class="fas fa-shopping-basket"></i>
            </div>
          </div>
        </a>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
</section>
<section class="cta-block">
  <div class="container">
    <div class="cta-grid">
      <div class="cta cta-1">
        <p>Offre du moment</p>
        <p>1 acheté, 1 offert</p>
        <p>Valable sur la nouvelle collection</p>
        <a href="#">En savoir plus</a>
      </div>
      <div class="cta cta-2">
        <p>Découvrez notre nouvelle collection</p>
        <p>Nouveaux vêtements bio</p>
        <p>Pour tous les goûts</p>
        <a href="#">En savoir plus</a>
      </div>
      <div class="cta cta-3">
        <p>Partenariat écologique</p>
        <p>Envoyez nous vos anciens vêtements</p>
        <p>20% de remise sur vos futurs achats</p>
        <a href="#">En savoir plus</a>
      </div>
      <div class="cta cta-4">
        <p>Découvrez notre application</p>
        <p>Commandez en toute sérénité n'importe où !</p>
        <p>Promotion lancement</p>
        <a href="#">En savoir plus</a>
      </div>
      <div class="cta cta-5">
        <p>Blog mode</p>
        <p>Les derniers tendances</p>
        <p>La mode dans le monde</p>
        <a href="#">En savoir plus</a>
      </div>
    </div>
  </div>
</section>

