<div class="create-account-block">  
    <div class="create-account">         
      <form action="index.php?action=create_account" method="POST">
          <h1>Creation d'un compte</h1>
          <?php if(isset($message)): ?>
            <p> <?= $message ?> </p>
          <?php endif; ?>
          <?php if(array_key_exists("message", $_GET)): ?>
            <p> <?= $_GET["message"] ?> </p>
          <?php endif; ?>
          <label><b>Nom d'utilisateur</b></label>
          <input type="text" placeholder="Entrer le nom d'utilisateur" name="username" required>
          <label><b>Nom</b></label>
          <input type="text" placeholder="Entrer le nom" name="lastname" required>
          <label><b>Prénom</b></label>
          <input type="text" placeholder="Entrer le prénom" name="name" required>
          <label><b>Télephone</b></label>
          <input type="text" placeholder="Entrer le numéro de téléphone" name="phone" required>
          <label><b>Email</b></label>
          <input type="mail" placeholder="Entrer l'email" name="email" required>
          <label><b>Adresse</b></label>
          <input type="text" placeholder="Entrer l'adresse" name="address" required>
          <label><b>Code postal</b></label>
          <input type="text" placeholder="Entrer le code postal" name="zip-code" required>
          <label><b>Pays</b></label>
          <input type="text" placeholder="Entrer le pays" name="city" required>
          <label><b>Date de naissance</b></label>
          <input type="date" placeholder="Entrer le date de naissance" name="birth" required>
          <label><b>Mot de passe</b></label>
          <input type="password" placeholder="Entrer le mot de passe" name="password" required>
          <input type="submit" value='CREER UN COMPTE' >
         
      </form>
    </div>
</div>