<div class="article-bg">
  <div class="container">
    <div class="flex-container">
      <div class="article-block">
        <h1>Blog Camiseta</h1>
        <?php foreach ($articlesList as $article) : ?>
          <div class="article-content">
            <h2><?= $article["title"] ?></h1>
              <p><em>Le <?= $article["date_create"] ?></em></p>
              <p><?= substr($article["content"], 0, 255) . '...' ?></p>
              <a href="index.php?action=details_article&id_article=<?= $article["id_article"] ?>"><button>En savoir plus</button></a>
          </div>
        <?php endforeach; ?>
      </div>
      <aside>
        <div class="article-comments">
          <h3>Commentaires</h3>
          <?php foreach ($comments as $comment) : ?>
            <div class="comments-content">
              <p>Posté par <?= $comment['last_name'] . " " . $comment['name'] ?></p>
              <p><em>Le <?= $comment['date_create'] ?></em></p>
              <p><?= $comment['content'] ?></p>
            </div>
          <?php endforeach; ?>
        </div>
      </aside>
    </div>

  </div>
</div>