<div class="article-bg">
  <div class="container">
    <h1>Blog Camiseta</h1>
    <div>
      <div class="article-content clearfix">
        <h2><?= $article["title"] ?></h1>
          <img src="<?= "views/" . $article["image_src"] ?>" alt="<?= $article["image_alt"]  ?>" class="align-right">
          <p><em>Le <?= $article["date_create"] ?></em></p>
          <p class="align-left"><?= nl2br($article["content"]) ?></p>
          <div class='action'>
            <a href="index.php?action=like&id_article=<?= $article['id_article'] ?>"><i class="fas fa-heart"></i><?= $likes ?></a>
            <a href="index.php?action=dislike&id_article=<?= $article['id_article'] ?>"><i class="fas fa-heart"></i><?= $dislikes ?></a>
          </div>
      </div>
    </div>
    <div class="form-comments">
      <form action="index.php?action=add_comment" method="post" class="form-features">
        <input type="hidden" name="id_article" value="<?= $article["id_article"]  ?>" />
        <div class="field">
          <label for="lastName">Nom</label>
          <input type="text" placeholder="Nom" name="last_name">
        </div>
        <div class="field">
          <label for="name">Prénom</label>
          <input type="text" placeholder="Prenom" name="name">
        </div>
        <div class="field relative">
          <label for="content">Votre commentaire</label>
          <textarea name="content" placeholder="La taille maximum pour un commentaire est de 300 caractères" id="comments"></textarea>
          <div class="lenght-comment" id="compteur">0</div>
        </div>
        <div class="field">
          <input type="submit" value="Ajouter">
        </div>
      </form>
    </div>
    <div class="article-comments">
      <h3>Commentaires</h3>
      <?php foreach ($comments as $comment) : ?>
        <div class="comments-content">
          <p>Posté par <?= $comment['last_name'] . " " . $comment['name'] ?></p>
          <p><em>Le <?= $comment['date_create'] ?></em></p>
          <p><?= $comment['content'] ?></p>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
</div>
<script>
  let comments = document.getElementById('comments')
  comments.addEventListener('keyup', function() {
    document.getElementById('compteur').innerHTML = comments.value.length;
  });
</script>