<div class="about-banner">
  <div class="about-banner-content">
    <p>#À propos</p>
    <p>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aperiam,
      perferendis.
    </p>
  </div>
</div>
<section class="about-section">
  <div class="container">
    <h1>Qui sommes-nous ?</h1>
    <div class="about-description">
      <img src="img/about/a6.jpg" alt="shopping" />
      <div>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit
          molestiae atque voluptates explicabo praesentium consectetur nesciunt
          consequuntur rem assumenda repellendus.
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur
          consequuntur magnam vel asperiores exercitationem soluta eos cumque quo
          culpa, deleniti maxime cupiditate. Similique, soluta atque.
        </p>
      </div>
    </div>
    <div class="about-app">
      <h2>
        Télécharger notre
        <a href="https://www.apple.com/fr/store"><span>application</span></a>
      </h2>
      <video src="img/about/1.mp4" type="video/mp4" autoplay loop></video>
    </div>
  </div>
</section>
<section class="features-block">
  <div class="container">
    <div class="features">
      <div class="fe-box">
        <img src="img/features/f1.png" alt="click & collect" />
        <p>Click & collect</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f2.png" alt="envoi gratuit" />
        <p>Envoi gratuit</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f3.png" alt="economie" />
        <p>Economie</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f4.png" alt="promotion" />
        <p>Promotions</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f5.png" alt="ecologique" />
        <p>Ecologique</p>
      </div>
      <div class="fe-box">
        <img src="img/features/f6.png" alt="SAV 24/24H" />
        <p>SAV 24/24H</p>
      </div>
    </div>
  </div>
</section>

