<div class="product-block">
  <div class="container">
    <div id="gallery" class="gallery">
      <div class="img-xl">
        <div>
          <img src="views/<?= $productDetails["image_src"] ?>" alt="<?= $productDetails["image_alt"] ?>">
        </div>
      </div>
      <ul class="img-sm">
        <li>
          <a href="views/<?= $productDetails["image_src"] ?>"><img src="views/<?= $productDetails["image_src"] ?>" alt="<?= $productDetails["image_alt"] ?>"></a>
        </li>
        <li>
          <a href="views/img/products/n5.jpg"><img src="views/img/products/n5.jpg" alt="Chemise"></a>
        </li>
        <li>
          <a href="views/img/products/n6.jpg"><img src="views/img/products/n6.jpg" alt="Short"></a>
        </li>
        <li>
          <a href="views/img/products/n7.jpg"><img src="views/img/products/n7.jpg" alt="Chemise"></a>
        </li>
      </ul>
    </div>
    <div class="product-details">
      <h2>Camiseta</h2>
      <h3><?= $productDetails["product_name"] ?></h3>
      <div class="product-detail">
        <p><em><?= $productDetails["product_alt"] ?></em></p>
        <p><span> A partir de <?= $productDetails["MSRP"] ?>€ </span><em>TVA incluse</em></p>
        <p><?= $productDetails["product_description"] ?></p>
        <div class="clearfix">
          <button>Ajouter au panier<i class="fas fa-shopping-bag"></i></button>
        </div>
      </div>
      <div class="product-delivery">
        <table>
          <tr>
            <td>Livraison <span>1 à 2 jours</span></td>
            <td>9,95 €</td>
          </tr>
          <tr>
            <td>Livraison express</td>
            <td>Gratuit à partir de <span>150 € d'achat</span></td>
          </tr>
          <tr>
            <td>Livré le <span><?= $deliveryDate ?></span></td>
            <td>Gratuit</td>
          </tr>
          <tr>
            <td>Livraison standard</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>