
<section class="catalogue ">
  <div class="container">
    <h1>Nos vêtements</h1>
    <div class="search-products-block">
      <form class="search-form">
        <div class="field">
          <input type="text" name="search" id="search" placeholder="Recherche d'articles">
          <i class="fas fa-search"></i>
        </div>
      </form>
      <div class="sort-button-block">
        <button id="sort-button">Filtrer & trier <i class="fas fa-sort"></i></button>
      </div>
    </div>
    <div class="products-block" id="search-result">
    </div>
    <div class="products-block" id="products">
      <?php foreach ($productsList as $product) : ?>
        <div class="product-box">
          <a href="index.php?action=detailsProduct&id_product=<?= $product["id_product"] ?>">
            <img src="views/<?= $product["image_src"] ?>" alt="<?= $product["image_alt"] ?>" />
            <div class="product-content">
              <div class="product-description">
                <h3>Camiseta</h3>
                <p><?= $product["product_name"] ?></p>
                <p><em><?= $product["product_alt"] ?></em></p>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
              </div>
              <div class="product-price">
                <p><?= $product["price"] ?> €</p>
              <?php if($this -> isConnectUser()) : ?>
                <a href="index.php?action=add_cart&id_user=<?= $_SESSION["user"]["id_user"] ?>&id_product=<?= $product["id_product"] ?>">
                  <i class="fas fa-shopping-basket"></i>
                </a>
              <?php endif; ?>
              </div>
            </div>
          </a>
        </div>
      <?php endforeach; ?>
    </div>
    <div class="products-content">
      <h2>Les chemises</h2>
      <div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, labore vero. Nostrum dolorem alias voluptatem quasi! Modi maiores nesciunt mollitia vitae iusto, asperiores inventore perferendis commodi magni quisquam ad facilis eligendi minima error, eius iste doloremque at expedita, tenetur ratione!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione qui sunt autem dignissimos accusamus, maiores unde voluptatem necessitatibus aliquid beatae?</p>
      </div>
      <h2>Les tuniques</h2>
      <div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, labore vero. Nostrum dolorem alias voluptatem quasi! Modi maiores nesciunt mollitia vitae iusto, asperiores inventore perferendis commodi magni quisquam ad facilis eligendi minima error, eius iste doloremque at expedita, tenetur ratione!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione qui sunt autem dignissimos accusamus, maiores unde voluptatem necessitatibus aliquid beatae?</p>
      </div>
      <h2>Les pantacourts</h2>
      <div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, labore vero. Nostrum dolorem alias voluptatem quasi! Modi maiores nesciunt mollitia vitae iusto, asperiores inventore perferendis commodi magni quisquam ad facilis eligendi minima error, eius iste doloremque at expedita, tenetur ratione!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione qui sunt autem dignissimos accusamus, maiores unde voluptatem necessitatibus aliquid beatae?</p>
      </div>
    </div>
  </div>
</section>
<div class="sort-modal" id="sort-modal">
  <div class="modal-head">
    <h2>Filtrer & trier</h2>
    <div id="sort-close">
      <button class="close"><i class="fas fa-times"></i></button>
    </div>
  </div>
  <div class="modal-body">
    <h3>Trier par</h3>
    <ul>
      <li><a href="index.php?action=productsSortByLowPrice">prix (bas/haut)</a></li>
      <li><a href="index.php?action=productsSortByHighPrice">prix (haut/bas)</a></li>
    </ul>
  </div>
</div>